name: Strava sync (commit outputs)

# grant the workflow explicit write permission to repo contents
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  run-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # allow pushing back using GITHUB_TOKEN
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas gspread oauth2client

      - name: Show repo root and list (debug)
        run: |
          echo "WORKDIR: $(pwd)"
          ls -la

      - name: Run Strava cyclists DB builder
        env:
          # Required credentials - set these in repo secrets
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
          # Optional overrides (set in repo secrets or leave defaults)
          OUTPUT_DB: cyclists.db
          CHECKPOINT_FILE: strava_profiles_checkpoint.json
          BATCH_SIZE: '50'
          MAX_RETRIES: '5'
          INITIAL_RETRY_SLEEP: '5'
        run: |
          set -eux
          # Prefer new script build_cyclists_db.py, fallback to older timepass.py if present
          if [ -f build_cyclists_db.py ]; then
            python build_cyclists_db.py
          elif [ -f timepass.py ]; then
            python timepass.py
          elif [ -f "timepass (2).py" ]; then
            python "timepass (2).py"
          else
            echo "ERROR: can't find build_cyclists_db.py or timepass.py" >&2
            exit 2
          fi

      - name: Show generated files (debug)
        run: |
          echo "DB file present?"
          ls -la cyclists.db || true
          echo "Checkpoint present?"
          ls -la strava_profiles_checkpoint.json || true

      - name: Commit and push outputs if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Only add the relevant files to avoid committing unrelated changes
          git add -A cyclists.db strava_profiles_checkpoint.json || true

          # If there are no changes, don't commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update Strava cyclists DB (runner: $RUNNER_NAME, time: $(date -u +'%Y-%m-%dT%H:%M:%SZ'))" || true
            git push origin HEAD:${{ github.ref_name }}
            echo "✅ Outputs committed and pushed"
          fi

      - name: Upload outputs as artifact (for convenience)
        uses: actions/upload-artifact@v4
        with:
          name: strava-exports
          path: |
            cyclists.db
            strava_profiles_checkpoint.json
