name: Download Strava last100 activities

# manual trigger
on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  download-last100:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: "strava_output"          # change if you want a different path
      OUT_CSV: "activities_last100.csv"
      OUT_JSON: "activities_last100.json"
      OUT_DB: "activities_last100.db"
      OUT_SQL: "activities_last100.sql"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Create output dir
        run: |
          mkdir -p "${{ env.OUTPUT_DIR }}"

      - name: Show env (for debug; removes secrets)
        run: |
          echo "OUTPUT_DIR=$OUTPUT_DIR"
          echo "Listing repo top-level:"
          ls -la

      - name: Run Strava downloader
        env:
          STRAVA_ACCESS_TOKEN: ${{ secrets.STRAVA_ACCESS_TOKEN }}
          OUTPUT_DIR: ${{ env.OUTPUT_DIR }}
        run: |
          # Ensure the script is present in repo root or adjust path
          chmod +x ./download_last100_strava.py || true
          python ./download_last100_strava.py

      - name: List output files
        run: |
          echo "Files in ${OUTPUT_DIR}:"
          ls -la "${OUTPUT_DIR}" || true

      - name: Upload outputs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: strava-last100-outputs
          path: |
            ${{ env.OUTPUT_DIR }}/activities_last100.csv
            ${{ env.OUTPUT_DIR }}/activities_last100.json
            ${{ env.OUTPUT_DIR }}/activities_last100.db
            ${{ env.OUTPUT_DIR }}/activities_last100.sql

      # Optional: commit generated files back to the repository
      # Note: enabling this will commit files using the GITHUB_TOKEN (no personal creds).
      # Remove or comment this step if you don't want auto-commits.
      - name: Commit outputs back to repo (optional)
        if: always()
        env:
          GIT_EMAIL: actions@github.com
          GIT_NAME: "github-actions[bot]"
        run: |
          git config user.email "${GIT_EMAIL}"
          git config user.name "${GIT_NAME}"
          git add "${{ env.OUTPUT_DIR }}" || true
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "chore: add/update Strava last100 outputs ($(date -u +'%Y-%m-%d %H:%M UTC'))" || true
            git push origin HEAD
          else
            echo "No changes to commit."
          fi
