name: Download all Strava athletes (with writeback)

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

# Increase job timeout if you expect long runs (minutes). Default is 360 for many orgs.
# timeout-minutes: 360

jobs:
  download-all:
    runs-on: ubuntu-latest
    # You may adjust timeout-minutes if your run is long (e.g., 360 = 6 hours)
    timeout-minutes: 360
    env:
      OUTPUT_DIR: "strava_output"
      # Optional: tune delay window here if you want different from script defaults
      DELAY_MIN: "02"
      DELAY_MAX: "03"
      PERSIST_EVERY: "10"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas gspread oauth2client

      - name: Create output dir
        run: |
          mkdir -p "${{ env.OUTPUT_DIR }}"

      - name: Run Strava download + sheet writeback
        env:
          # Required secrets — set these in repo Settings -> Secrets & variables -> Actions
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          # Optional: If you want to override the script's defaults:
          OUTPUT_DIR: ${{ env.OUTPUT_DIR }}
          DELAY_MIN: ${{ env.DELAY_MIN }}
          DELAY_MAX: ${{ env.DELAY_MAX }}
          PERSIST_EVERY: ${{ env.PERSIST_EVERY }}
        run: |
          if [ ! -f ./download_all_with_writeback.py ]; then
            echo "ERROR: download_all_with_writeback.py not found in repo root"
            exit 2
          fi
          python ./download_all_with_writeback.py

      - name: List outputs
        run: |
          echo "Contents of ${{ env.OUTPUT_DIR }}:"
          ls -la "${{ env.OUTPUT_DIR }}" || true

      - name: Upload outputs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: strava-all-athletes-outputs
          path: |
            ${{ env.OUTPUT_DIR }}/*

      - name: Commit outputs back to repository
        if: always()
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: actions@github.com
          # GITHUB_TOKEN is provided automatically by GitHub actions
        run: |
          git config user.name "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
          # Add files in output dir
          git add "${{ env.OUTPUT_DIR }}" || true
          # Only commit when there are changes
          if ! git diff --cached --quiet; then
            git commit -m "chore: update Strava outputs & sheet writeback ($(date -u +'%Y-%m-%d %H:%M UTC'))" || true
            # push using the automatically provided token
            git push origin HEAD || echo "Push failed (maybe branch protection prevents pushing)."
          else
            echo "No changes to commit."
          fi
