name: Strava sync (matrix)

on:
  workflow_dispatch:

permissions:
  contents: write   # required only if you want the workflow to commit files back to repo

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python deps (for matrix generation)
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client

      - name: Generate athlete matrix JSON
        id: gen-matrix
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
        run: |
          python - <<'PY' > athletes.json
          import os, json
          import gspread
          from oauth2client.service_account import ServiceAccountCredentials

          def get_cell_str(row, *keys):
              """Return first matching key from row as a stripped string (safe for ints/None)."""
              for k in keys:
                  if k in row and row[k] is not None:
                      return str(row[k]).strip()
              return ""

          # load creds and open sheet
          creds = json.loads(os.environ["GOOGLE_SHEETS_JSON"])
          scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
          credentials = ServiceAccountCredentials.from_json_keyfile_dict(creds, scope)
          client = gspread.authorize(credentials)
          sheet = client.open_by_url(os.environ["SHEET_URL"]).sheet1
          rows = sheet.get_all_records()

          include = []
          for r in rows:
              # try several possible column names for Athlete ID (safe conversion)
              aid = get_cell_str(r, "Athlete ID", "AthleteID", "Athlete Id", "athlete id", "Athlete_Id")
              # OPTIONAL: require a refresh token to avoid runs for rows without credentials
              # refresh = get_cell_str(r, "Refresh Token", "RefreshToken", "refresh token")
              # if aid and refresh:
              if aid:
                  include.append({"athlete_id": aid})

          out = {"include": include}
          print(json.dumps(out))
          PY
          cat athletes.json

      - name: Set matrix output for downstream jobs
        id: set-matrix
        run: |
          echo "matrix=$(cat athletes.json)" >> $GITHUB_OUTPUT

  run-athlete:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix).include }}
      max-parallel: 2   # ADJUST: set to 1 or 2 if Strava rate limits are a concern
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true   # adjust to your deps (pandas, requests, etc.)

      - name: Run download for athlete
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          TARGET_ATHLETE_ID: ${{ matrix.athlete_id }}
        run: |
          echo "Starting sync for athlete: $TARGET_ATHLETE_ID"
          python download_one_from_sheet.py

      - name: Commit outputs (optional)
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add strava_output || true
          git commit -m "Strava outputs: $TARGET_ATHLETE_ID" || echo "no changes to commit"
          git push || echo "push failed (maybe permissions)"
