name: Strava Sync

on:
  schedule:
    - cron: "*/15 * * * *"   # Every 15 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Strava batch extractor
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}

          # Optional configs
          BATCH_SIZE: "50"
          CHECKPOINT_FILE: "strava_checkpoint.json"
          OUTPUT_CSV: "athlete_data.csv"
          OUTPUT_JSON: "athlete_data.json"
        run: |
          python timepass.py

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: strava-data
          path: |
            athlete_data.csv
            athlete_data.json
            strava_checkpoint.json
