      - name: Download latest CSV
        run: curl -L -o activities.csv https://raw.githubusercontent.com/manojcpatil/jalgaon-cyclists-club/refs/heads/main/strava_output/athlete_32305502_20251003.csv

      - name: Run uploader
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_ACCESS_TOKEN: ${{ secrets.STRAVA_ACCESS_TOKEN }}
        run: |
          python strava_upload_from_csv.py --csv activities.csv
